# Generated by Django 5.2.8 on 2025-11-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='floors',
            field=models.PositiveIntegerField(blank=True, help_text='Number of floors (for houses)', null=True),
        ),
    ]
