# Generated by Django 5.2.6 on 2025-09-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("real_estate", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="property",
            name="longitude",
        ),
        migrations.AddField(
            model_name="property",
            name="area",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="property",
            name="polygon",
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="property",
            name="price",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="property",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="property",
            name="title",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
