# Generated by Django 5.2.8 on 2025-11-06 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0002_property_floors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='property',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='property',
            name='maintenance_fee',
        ),
    ]
