# Generated by Django 5.2.8 on 2025-11-06 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0003_remove_property_contact_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='main_image',
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/')),
                ('is_main', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='real_estate.property')),
            ],
            options={
                'ordering': ['-is_main', '-uploaded_at'],
            },
        ),
    ]
