# Generated by Django 5.2.8 on 2025-11-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0004_remove_property_main_image_propertyimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('for_sale', 'For Sale'), ('for_rent', 'For Rent'), ('inactive', 'Inactive')], default='for_sale', max_length=30),
        ),
    ]
