# Generated by Django 5.2.8 on 2025-11-18 19:36

import real_estate.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0005_alter_property_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='file_size',
            field=models.IntegerField(default=0, help_text='Tamaño del archivo en bytes'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Thumbnail optimizado para previsualizaciones', null=True, upload_to='properties/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to='properties/', validators=[real_estate.validators.validate_image_size, real_estate.validators.validate_image_dimensions, real_estate.validators.validate_image_format]),
        ),
    ]
