# Generated by Django 5.2.11 on 2026-02-12 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0010_user_oauth_fields'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE real_estate_property
                        ADD COLUMN IF NOT EXISTS show_measurements boolean;

                        ALTER TABLE real_estate_property
                        ALTER COLUMN show_measurements SET DEFAULT true;

                        UPDATE real_estate_property
                        SET show_measurements = true
                        WHERE show_measurements IS NULL;

                        ALTER TABLE real_estate_property
                        ALTER COLUMN show_measurements SET NOT NULL;
                    """,
                    reverse_sql="""
                        ALTER TABLE real_estate_property
                        DROP COLUMN IF EXISTS show_measurements;
                    """,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='property',
                    name='show_measurements',
                    field=models.BooleanField(
                        default=True,
                        help_text='Show exact measurements on map or just reference figure',
                    ),
                ),
            ],
        ),
    ]
