# Generated by Django 6.0.6 on 2026-07-07 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingesta', '0001_initial'),
        ('real_estate', '0014_pendingpublication'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='property',
            name='dedup_key',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Huella de rejilla geográfica para deduplicar', max_length=64),
        ),
        migrations.AddField(
            model_name='property',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='ID del anuncio en el portal de origen', max_length=120),
        ),
        migrations.AddField(
            model_name='property',
            name='imported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='is_imported',
            field=models.BooleanField(db_index=True, default=False, help_text='True si fue recopilada por el agregador'),
        ),
        migrations.AddField(
            model_name='property',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, help_text='Última vez visto en la fuente (para caducar)', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='source',
            field=models.ForeignKey(blank=True, help_text='Portal de origen si la propiedad fue importada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='ingesta.fuente'),
        ),
        migrations.AddField(
            model_name='property',
            name='source_url',
            field=models.URLField(blank=True, default='', help_text='Enlace al anuncio original (contacto fallback)', max_length=500),
        ),
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.FloatField(blank=True, help_text='Total area in square meters (opcional en anuncios importados)', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Opcional: los anuncios importados pueden no traer precio ('a consultar')", max_digits=12, null=True),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.UniqueConstraint(condition=models.Q(('is_imported', True)), fields=('source', 'external_id'), name='uniq_source_external_when_imported'),
        ),
    ]
