# Generated by Django 6.0.6 on 2026-07-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0015_property_contact_email_property_dedup_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='source_agency',
            field=models.CharField(blank=True, default='', help_text='Inmobiliaria/publicador del anuncio en el portal de origen', max_length=150),
        ),
    ]
