# Generated by Django 6.0.6 on 2026-07-07 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0016_property_source_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, help_text='Propiedad canónica (la que sí se muestra) de la que este anuncio es duplicado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='real_estate.property'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_duplicate',
            field=models.BooleanField(db_index=True, default=False, help_text='Oculto del mapa: es duplicado de otra fuente (perdió la preferencia)'),
        ),
    ]
