# Generated by Django 6.0.6 on 2026-07-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0017_property_duplicate_of_property_is_duplicate'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image_hash',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Huella perceptual (dHash) de la imagen principal, para detectar la misma propiedad entre portales', max_length=32),
        ),
    ]
