# Generated by Django 6.0.6 on 2026-07-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0018_property_image_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='rent_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio de alquiler cuando el anuncio es venta Y alquiler a la vez', max_digits=12, null=True),
        ),
    ]
