# Generated by Django 6.0.7 on 2026-08-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0024_declared_indexes_catchup'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityevent',
            name='is_bot',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
