# Generated by Django 6.0.7 on 2026-08-04 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0027_backfill_polygon_centers'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingpublication',
            name='property',
            field=models.ForeignKey(blank=True, help_text='Propiedad creada al canjear el enlace de continuación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_publications', to='real_estate.property'),
        ),
        migrations.CreateModel(
            name='PublicationResumeToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_resume_tokens', to=settings.AUTH_USER_MODEL)),
                ('pending', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_tokens', to='real_estate.pendingpublication')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['pending', '-created_at'], name='resume_pending_created_idx')],
            },
        ),
    ]
