# Generated by Django 6.0.7 on 2026-08-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0029_property_short_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='closed_at',
            field=models.DateTimeField(blank=True, help_text='Cuándo se cerró el anuncio; se rellena solo al marcar el motivo', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='closed_reason',
            field=models.CharField(blank=True, choices=[('sold', 'Sold'), ('rented', 'Rented'), ('withdrawn', 'Withdrawn')], db_index=True, default='', help_text='Por qué se cerró el anuncio: vendido, alquilado o retirado. Vacío = sigue abierto', max_length=20),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['property', 'is_bot', 'created_at'], name='activity_prop_human_idx'),
        ),
    ]
