# Generated by Django 6.0.8 on 2026-08-20 03:41

from django.db import migrations, models

from real_estate.models import sector_key


def fill_sectors(apps, schema_editor):
    """Backfill the zone of every listing already published.

    In batches and with `update`, not `save()`: this runs over the whole
    catalogue and a per-row save would fire the rest of the model logic and
    move `updated_at`, which feeds the sitemap's `lastmod` (SEO-006). A
    backfill is not a change to the listing.
    """
    Property = apps.get_model("real_estate", "Property")
    batch = []
    for row in Property.objects.only("id", "address", "city").iterator(chunk_size=2000):
        key = sector_key(row.address, row.city)
        label = (row.address or "").split(",")[0].strip() if key else ""
        if (row.sector_key, row.sector_label) == (key, label):
            continue
        row.sector_key, row.sector_label = key, label
        batch.append(row)
        if len(batch) >= 2000:
            Property.objects.bulk_update(batch, ["sector_key", "sector_label"])
            batch = []
    if batch:
        Property.objects.bulk_update(batch, ["sector_key", "sector_label"])


def clear_sectors(apps, schema_editor):
    apps.get_model("real_estate", "Property").objects.update(sector_key="", sector_label="")


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0034_search_and_dedup_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='sector_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='property',
            name='sector_label',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.RunPython(fill_sectors, clear_sectors),
    ]
