# Generated by Django 6.0.8 on 2026-08-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0035_property_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_on', models.DateField(db_index=True)),
                ('scope', models.CharField(choices=[('country', 'País'), ('city', 'Ciudad'), ('sector', 'Zona')], max_length=10)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('sector_key', models.CharField(blank=True, default='', max_length=120)),
                ('property_type', models.CharField(blank=True, default='', max_length=30)),
                ('status', models.CharField(max_length=20)),
                ('active_count', models.PositiveIntegerField()),
                ('median_price', models.FloatField(blank=True, null=True)),
                ('avg_price', models.FloatField(blank=True, null=True)),
                ('median_price_m2', models.FloatField(blank=True, null=True)),
                ('avg_price_m2', models.FloatField(blank=True, null=True)),
                ('median_area', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Corte de mercado',
                'verbose_name_plural': 'Cortes de mercado',
                'ordering': ['-captured_on', 'scope', 'city', 'sector_key'],
                'indexes': [models.Index(fields=['scope', 'city', 'sector_key', 'property_type', 'status', 'captured_on'], name='snapshot_series_idx')],
                'constraints': [models.UniqueConstraint(fields=('captured_on', 'scope', 'city', 'sector_key', 'property_type', 'status'), name='unique_market_snapshot_slice')],
            },
        ),
    ]
