# Generated by Django 6.0.8 on 2026-08-21 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0039_reject_seller_voice_headlines'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Momento en que se envió a la papelera; nulo si está viva', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='deleted_previous_status',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.CreateModel(
            name='ActivityDailyRollup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('event_name', models.CharField(max_length=100)),
                ('is_bot', models.BooleanField(default=False)),
                ('events', models.PositiveIntegerField(default=0)),
                ('sessions', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-day', 'event_name'],
                'indexes': [models.Index(fields=['day', 'is_bot'], name='rollup_day_bot_idx')],
                'constraints': [models.UniqueConstraint(fields=('day', 'event_name', 'is_bot'), name='unique_activity_rollup_slice')],
            },
        ),
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_label', models.CharField(blank=True, default='', max_length=150)),
                ('action', models.CharField(db_index=True, max_length=60)),
                ('target_type', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('target_id', models.CharField(blank=True, default='', max_length=40)),
                ('target_label', models.CharField(blank=True, default='', max_length=250)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', '-created_at'], name='audit_action_date_idx'), models.Index(fields=['target_type', 'target_id'], name='audit_target_idx'), models.Index(fields=['actor', '-created_at'], name='audit_actor_date_idx')],
            },
        ),
    ]
