# Generated by Django 6.0.8 on 2026-08-22 01:50

from django.db import migrations, models


def backfill_normalized_phones(apps, schema_editor):
    """Fill the lookup column for listings that already exist.

    Without this the claim flow would only see properties saved after the
    deploy — which is none of the fifteen thousand imported ones the whole
    feature is for. Done in batches because the table is large and this runs
    inside the deploy's migration step, where a long lock is a visible outage.
    """
    from real_estate.services.phones import normalize_ec_phone

    Property = apps.get_model("real_estate", "Property")
    batch = []
    rows = Property.objects.exclude(contact_phone="").only("id", "contact_phone")
    for prop in rows.iterator(chunk_size=2000):
        normalized = normalize_ec_phone(prop.contact_phone)
        if not normalized:
            continue
        prop.contact_phone_normalized = normalized
        batch.append(prop)
        if len(batch) >= 2000:
            Property.objects.bulk_update(batch, ["contact_phone_normalized"])
            batch = []
    if batch:
        Property.objects.bulk_update(batch, ["contact_phone_normalized"])


def drop_normalized_phones(apps, schema_editor):
    """Reversing only clears the derived column; nothing original is lost."""
    apps.get_model("real_estate", "Property").objects.update(contact_phone_normalized="")


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0040_admin_trash_audit_and_activity_rollup'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='contact_phone_normalized',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_normalized_phones, drop_normalized_phones),
    ]
