# Generated by Django 6.0.8 on 2026-08-22 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0041_claimable_imported_listings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimDismissal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_dismissals', to='real_estate.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_dismissals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'descarte de reclamo',
                'verbose_name_plural': 'descartes de reclamo',
                'constraints': [models.UniqueConstraint(fields=('user', 'property'), name='uniq_claim_dismissal_user_property')],
            },
        ),
    ]
