"""Shared loading and consistency checks for the YAML specs under specs/.

The specs are the source of truth for business rules. Everything else — the
generated docs, the generated tests, the CI gate — reads from here, so this
module is deliberately strict: a spec that cannot be trusted is worse than no
spec at all.

The check that gives the system its teeth is `check_evidence`. A rule marked as
`implemented` must point at the code that enforces it, and that pointer is
verified: the file has to exist, the line range has to fit inside it, and the
named symbol has to still be there. Delete or rename the enforcement and CI
fails with the rule id, which is how a spec stays honest as the code moves.
"""

from __future__ import annotations

import json
import re
import unicodedata
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Iterable

try:
    import yaml
except ModuleNotFoundError as exc:  # pragma: no cover - environment guard
    raise SystemExit(
        "PyYAML is not installed. Run ./scripts/specs.sh bootstrap "
        "(it creates .venv-specs with the dependencies)."
    ) from exc


REPO_ROOT = Path(__file__).resolve().parents[2]
SPECS_DIR = REPO_ROOT / "specs"
SCHEMA_PATH = SPECS_DIR / "schemas" / "rule.schema.json"

# Directories inside specs/ that are not spec files themselves.
EXCLUDED_DIRS = {"schemas", "proposals"}

# Statuses that mean "the code does this today".
LIVE_STATUSES = {"implemented", "partial"}
# Statuses that mean "no code does this", so evidence would be a lie.
UNBUILT_STATUSES = {"proposed", "not_implemented"}

# Where each generated artefact goes. API and unit tests land inside backend/
# on purpose: the suite runs in the backend container, which only bind-mounts
# ./backend, so a repo-root tests/api directory would be invisible to pytest.
GENERATED_DOCS_DIR = REPO_ROOT / "docs" / "generated"
GENERATED_PYTEST_DIR = REPO_ROOT / "backend" / "real_estate" / "tests" / "generated"
GENERATED_E2E_DIR = REPO_ROOT / "tests" / "generated"

# Directories scanned for the SPEC:<id> traceability markers.
TEST_SEARCH_DIRS = (
    REPO_ROOT / "backend" / "real_estate" / "tests",
    REPO_ROOT / "backend" / "ingesta" / "tests",
    REPO_ROOT / "backend" / "blog" / "tests",
    REPO_ROOT / "backend" / "advertising" / "tests",
    REPO_ROOT / "tests",
    REPO_ROOT / "frontend" / "components",
    REPO_ROOT / "frontend" / "lib",
)

SPEC_MARKER_RE = re.compile(r"SPEC:([A-Z]{2,6}-[0-9]{3})")

GENERATED_BANNER = "GENERATED BY tools/specs — DO NOT EDIT BY HAND"


@dataclass
class Problem:
    """A single validation failure, reported with enough context to act on it."""

    where: str
    message: str
    level: str = "error"

    def __str__(self) -> str:
        mark = "ERROR" if self.level == "error" else "WARN"
        return f"[{mark}] {self.where}: {self.message}"


@dataclass
class SpecFile:
    path: Path
    data: dict[str, Any]

    @property
    def rel(self) -> str:
        return str(self.path.relative_to(REPO_ROOT))

    @property
    def domain(self) -> str:
        return self.data.get("domain", "")

    @property
    def rules(self) -> list[dict[str, Any]]:
        return self.data.get("rules", []) or []

    @property
    def catalog(self) -> dict[str, Any]:
        return self.data.get("catalog", {}) or {}


@dataclass
class SpecSet:
    """Every spec file plus the vocabularies they collectively declare."""

    files: list[SpecFile] = field(default_factory=list)

    def rules(self) -> Iterable[tuple[SpecFile, dict[str, Any]]]:
        for spec in self.files:
            for rule in spec.rules:
                yield spec, rule

    def rule_by_id(self, rule_id: str) -> dict[str, Any] | None:
        for _spec, rule in self.rules():
            if rule.get("id") == rule_id:
                return rule
        return None

    def permission_slugs(self) -> set[str]:
        slugs: set[str] = set()
        for spec in self.files:
            for entry in spec.catalog.get("permissions", []) or []:
                slugs.add(entry["slug"])
        return slugs

    def error_codes(self) -> dict[str, dict[str, Any]]:
        codes: dict[str, dict[str, Any]] = {}
        for spec in self.files:
            for entry in spec.catalog.get("error_codes", []) or []:
                codes[entry["code"]] = entry
        return codes


def spec_paths() -> list[Path]:
    if not SPECS_DIR.exists():
        return []
    paths = []
    for path in sorted(SPECS_DIR.rglob("*.yaml")):
        rel_parts = path.relative_to(SPECS_DIR).parts
        if rel_parts[0] in EXCLUDED_DIRS:
            continue
        paths.append(path)
    return paths


def load_specs() -> tuple[SpecSet, list[Problem]]:
    """Parse every spec file. Parse errors are returned, never raised."""

    specs = SpecSet()
    problems: list[Problem] = []
    for path in spec_paths():
        rel = str(path.relative_to(REPO_ROOT))
        try:
            data = yaml.safe_load(path.read_text(encoding="utf-8"))
        except yaml.YAMLError as exc:
            problems.append(Problem(rel, f"invalid YAML: {exc}"))
            continue
        if not isinstance(data, dict):
            problems.append(Problem(rel, "the file must be a YAML mapping at the root"))
            continue
        specs.files.append(SpecFile(path=path, data=data))
    return specs, problems


def check_schema(specs: SpecSet) -> list[Problem]:
    """Validate every file against specs/schemas/rule.schema.json."""

    try:
        import jsonschema
    except ModuleNotFoundError:
        return [
            Problem(
                "tools/specs",
                "jsonschema is not installed; schema validation was skipped. "
                "Run ./scripts/specs.sh bootstrap.",
                level="warning",
            )
        ]

    schema = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))
    validator = jsonschema.Draft202012Validator(schema)
    problems: list[Problem] = []
    for spec in specs.files:
        for error in sorted(validator.iter_errors(spec.data), key=lambda e: list(e.path)):
            location = "/".join(str(part) for part in error.path) or "(root)"
            problems.append(Problem(f"{spec.rel} → {location}", error.message))
    return problems


def check_file_naming(specs: SpecSet) -> list[Problem]:
    problems: list[Problem] = []
    for spec in specs.files:
        expected = spec.path.stem
        if spec.domain and spec.domain != expected:
            problems.append(
                Problem(
                    spec.rel,
                    f"domain '{spec.domain}' does not match the file name '{expected}'",
                )
            )
    return problems


def check_unique_ids(specs: SpecSet) -> list[Problem]:
    seen: dict[str, str] = {}
    problems: list[Problem] = []
    for spec, rule in specs.rules():
        rule_id = rule.get("id")
        if not rule_id:
            continue
        if rule_id in seen:
            problems.append(
                Problem(spec.rel, f"duplicate id '{rule_id}' (already defined in {seen[rule_id]})")
            )
        else:
            seen[rule_id] = spec.rel
    return problems


def _line_count(path: Path) -> int:
    with path.open("rb") as handle:
        return sum(1 for _ in handle)


def check_evidence(specs: SpecSet) -> list[Problem]:
    """The anchor between spec and code.

    A rule that claims to be enforced must say where. The pointer is verified
    against the working tree, so refactoring the enforcement away turns into a
    failing check instead of a spec that quietly starts lying.
    """

    problems: list[Problem] = []
    for spec, rule in specs.rules():
        rule_id = rule.get("id", "?")
        where = f"{spec.rel} → {rule_id}"
        status = rule.get("status")
        evidence = rule.get("evidence") or []

        if status in LIVE_STATUSES and not evidence:
            problems.append(
                Problem(where, f"status '{status}' requires at least one 'evidence' entry")
            )
        if status in UNBUILT_STATUSES and evidence:
            problems.append(
                Problem(
                    where,
                    f"status '{status}' cannot carry 'evidence': no code backs it",
                )
            )

        for item in evidence:
            rel_file = item.get("file", "")
            target = REPO_ROOT / rel_file
            if not target.exists():
                problems.append(Problem(where, f"evidence points at a missing file: {rel_file}"))
                continue
            if target.is_dir():
                continue

            lines = item.get("lines")
            if lines:
                start, _, end = lines.partition("-")
                start_n = int(start)
                end_n = int(end) if end else start_n
                total = _line_count(target)
                if start_n < 1 or end_n < start_n:
                    problems.append(Problem(where, f"invalid line range '{lines}' in {rel_file}"))
                elif end_n > total:
                    problems.append(
                        Problem(
                            where,
                            f"{rel_file} has {total} lines, but the evidence cites up to {end_n}",
                        )
                    )

            symbol = item.get("symbol")
            if symbol:
                try:
                    content = target.read_text(encoding="utf-8", errors="replace")
                except OSError as exc:
                    problems.append(Problem(where, f"could not read {rel_file}: {exc}"))
                    continue
                if symbol not in content:
                    problems.append(
                        Problem(
                            where,
                            f"symbol '{symbol}' no longer appears in {rel_file} "
                            "(was the enforcement renamed or removed?)",
                        )
                    )
                elif lines:
                    # The symbol has to sit inside the cited range, not merely
                    # somewhere in the file. Without this the green tick is
                    # worthless: a range can point at unrelated code forever
                    # while the symbol matches a hit hundreds of lines away.
                    src = content.splitlines()
                    start, _, end = lines.partition("-")
                    start_n = max(1, int(start))
                    end_n = int(end) if end else start_n
                    excerpt = "\n".join(src[start_n - 1 : end_n])
                    if symbol not in excerpt:
                        actual = _find_symbol_lines(src, symbol)
                        hint = (
                            f" (it is on line {actual[0]})"
                            if len(actual) == 1
                            else f" (it is on lines {', '.join(map(str, actual[:5]))})"
                            if actual
                            else ""
                        )
                        problems.append(
                            Problem(
                                where,
                                f"the range {rel_file}:{lines} does not contain "
                                f"'{symbol}'{hint}. Run ./scripts/specs.sh fix-ranges "
                                "to re-anchor it.",
                            )
                        )
    return problems


def _find_symbol_lines(src: list[str], symbol: str) -> list[int]:
    """1-indexed lines where the symbol appears, for the error hint."""
    return [index for index, line in enumerate(src, start=1) if symbol in line]


def check_vocabularies(specs: SpecSet) -> list[Problem]:
    """Permissions and error codes must be declared before they are used."""

    problems: list[Problem] = []
    permissions = specs.permission_slugs()
    error_codes = set(specs.error_codes())

    for spec, rule in specs.rules():
        where = f"{spec.rel} → {rule.get('id', '?')}"
        for slug in (rule.get("permissions", {}) or {}).get("required", []) or []:
            if slug not in permissions:
                problems.append(
                    Problem(where, f"permission '{slug}' is not declared in specs/permissions/matrix.yaml")
                )
        backend = rule.get("backend", {}) or {}
        code = backend.get("denied_error_code")
        if code and code not in error_codes:
            problems.append(
                Problem(where, f"error_code '{code}' is not declared in specs/errors/catalog.yaml")
            )
        for case in rule.get("cases", []) or []:
            case_code = case.get("error_code")
            if case_code and case_code not in error_codes:
                problems.append(
                    Problem(
                        f"{where} -> case '{case.get('name')}'",
                        f"error_code '{case_code}' is not declared in specs/errors/catalog.yaml",
                    )
                )
    return problems


# HTTP methods that carry no request body.
BODYLESS_METHODS = {"GET", "DELETE", "HEAD", "OPTIONS"}


def check_case_shape(specs: SpecSet) -> list[Problem]:
    """`given` is the world before the call; `body` is the call.

    They used to be one field, and the confusion was invisible: a `given` on a
    GET was dropped by the harness, so the case ran against the default world
    and passed for the wrong reason. Both halves of that mistake are caught
    here — a body no request can carry, and a precondition on a method whose
    `given` used to mean the payload.
    """

    problems: list[Problem] = []
    for spec, rule in specs.rules():
        backend = rule.get("backend", {}) or {}
        rule_endpoint = backend.get("endpoint")
        api_tested = bool((rule.get("tests") or {}).get("api"))
        for case in rule.get("cases", []) or []:
            where = f"{spec.rel} → {rule.get('id', '?')} → case '{case.get('name')}'"
            case_endpoint = case.get("endpoint")
            if case_endpoint and not rule_endpoint:
                problems.append(
                    Problem(
                        where,
                        "the case overrides 'endpoint' but the rule declares no "
                        "'backend.endpoint', so the generator skips it entirely",
                    )
                )
            endpoint = case_endpoint or rule_endpoint
            if not endpoint:
                continue
            method = endpoint.split(" ", 1)[0]
            if method in BODYLESS_METHODS and case.get("body"):
                problems.append(
                    Problem(where, f"declares a 'body' but {method} carries none")
                )
            executable = (
                api_tested
                and case.get("role")
                and case.get("expected") in {"allowed", "denied"}
            )
            if executable and method not in BODYLESS_METHODS and case.get("given"):
                problems.append(
                    Problem(
                        where,
                        f"has a 'given' on a {method}, where it used to mean the request "
                        "payload. If it describes the state before the call, leave it and "
                        "teach SpecWorld.apply to build it; if it is the payload, it "
                        "belongs in 'body'.",
                        level="warning",
                    )
                )
    return problems


def check_status_coherence(specs: SpecSet) -> list[Problem]:
    problems: list[Problem] = []
    for spec in specs.files:
        domain_status = spec.data.get("status")
        if domain_status not in UNBUILT_STATUSES:
            continue
        for rule in spec.rules:
            if rule.get("status") in LIVE_STATUSES:
                problems.append(
                    Problem(
                        f"{spec.rel} → {rule.get('id', '?')}",
                        f"the domain is marked '{domain_status}' but the rule says "
                        f"'{rule.get('status')}'",
                    )
                )
    return problems


def collect_spec_markers() -> dict[str, set[str]]:
    """Map rule id -> set of files that carry a SPEC:<id> marker."""

    markers: dict[str, set[str]] = {}
    for base in TEST_SEARCH_DIRS:
        if not base.exists():
            continue
        for path in base.rglob("*"):
            if not path.is_file() or path.suffix not in {".py", ".ts", ".tsx", ".js", ".jsx"}:
                continue
            if "node_modules" in path.parts or "__pycache__" in path.parts:
                continue
            try:
                content = path.read_text(encoding="utf-8", errors="replace")
            except OSError:
                continue
            for rule_id in SPEC_MARKER_RE.findall(content):
                markers.setdefault(rule_id, set()).add(str(path.relative_to(REPO_ROOT)))
    return markers


def check_test_coverage(specs: SpecSet) -> list[Problem]:
    """Every live rule that asks for a test layer must actually have one.

    The link is a `SPEC:<id>` marker in the test source. Generated tests carry
    it automatically; hand-written ones have to add it, which is what keeps a
    rule from being declared covered by a test that no longer exercises it.
    """

    problems: list[Problem] = []
    markers = collect_spec_markers()
    for spec, rule in specs.rules():
        if rule.get("status") not in LIVE_STATUSES:
            continue
        wanted = rule.get("tests", {}) or {}
        if not any(wanted.values()):
            continue
        rule_id = rule.get("id", "?")
        if rule_id not in markers:
            layers = ", ".join(sorted(k for k, v in wanted.items() if v))
            problems.append(
                Problem(
                    f"{spec.rel} → {rule_id}",
                    f"asks for coverage ({layers}) but no test carries the SPEC:{rule_id} marker",
                )
            )
    return problems


def validate(specs: SpecSet) -> list[Problem]:
    checks = (
        check_schema,
        check_file_naming,
        check_unique_ids,
        check_case_shape,
        check_status_coherence,
        check_evidence,
        check_vocabularies,
        check_test_coverage,
    )
    problems: list[Problem] = []
    for check in checks:
        problems.extend(check(specs))
    return problems


def write_if_changed(path: Path, content: str) -> bool:
    """Write only on a real change, so --check can diff generated output."""

    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    path.write_text(content, encoding="utf-8")
    return True


def slug_to_identifier(value: str) -> str:
    """Turn a Spanish rule or case name into a readable Python identifier.

    Accents are folded rather than dropped: without this, "anónimo" becomes
    "an_nimo" in the generated test name, which is hard to read in a pytest
    failure line.
    """
    folded = unicodedata.normalize("NFKD", value)
    ascii_only = "".join(char for char in folded if not unicodedata.combining(char))
    return re.sub(r"[^0-9a-zA-Z]+", "_", ascii_only).strip("_").lower()
