# Generated by Django 6.0.8 on 2026-08-12 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('website', models.URLField(verbose_name='Sitio web')),
                ('tagline', models.CharField(blank=True, help_text='Una línea sobre qué hace. Aparece bajo el nombre.', max_length=200, verbose_name='Descriptor')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='advertising/advertisers/', verbose_name='Logotipo')),
                ('logo_alt', models.CharField(blank=True, max_length=200, verbose_name='Texto alternativo del logotipo')),
                ('contact_name', models.CharField(blank=True, max_length=120, verbose_name='Contacto')),
                ('contact_phone', models.CharField(blank=True, help_text='A quién se le escribe para renovar.', max_length=40, verbose_name='Teléfono de contacto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Anunciante',
                'verbose_name_plural': 'Anunciantes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.CharField(choices=[('index_top', 'Blog — bajo la cabecera'), ('index_feed', 'Blog — dentro de la rejilla de artículos'), ('post_inline', 'Artículo — a mitad del texto'), ('post_footer', 'Artículo — bajo el contenido'), ('category_top', 'Categoría — bajo la cabecera'), ('home_feed', 'Inicio — dentro de la lista de resultados'), ('city_hero', 'Ciudad o provincia — bajo la cabecera'), ('listing_feed', 'Listados — dentro de la rejilla'), ('property_sidebar', 'Ficha — bajo el bloque de contacto'), ('property_footer', 'Ficha — antes de las similares'), ('stats_inline', 'Estadísticas — entre secciones'), ('site_footer', 'Pie de página — aliados')], db_index=True, max_length=20, verbose_name='Ubicación')),
                ('kind', models.CharField(choices=[('paid', 'Pagada'), ('partner', 'Del grupo (sin coste)'), ('promo', 'Espacio disponible')], db_index=True, default='paid', max_length=10, verbose_name='Clase')),
                ('headline', models.CharField(max_length=120, verbose_name='Titular')),
                ('body', models.TextField(help_text='Dos o tres líneas. Texto plano, sin Markdown.', max_length=400, verbose_name='Texto')),
                ('cta_label', models.CharField(default='Saber más', max_length=60, verbose_name='Texto del botón')),
                ('target_url', models.URLField(blank=True, help_text='El enlace sale siempre con rel="sponsored nofollow". Vacío en el reclamo propio.', verbose_name='URL de destino')),
                ('image', models.ImageField(blank=True, null=True, upload_to='advertising/campaigns/', verbose_name='Imagen')),
                ('image_alt', models.CharField(blank=True, max_length=200, verbose_name='Texto alternativo de la imagen')),
                ('starts_at', models.DateTimeField(blank=True, help_text='Vacío = activa desde ya. Hora en UTC (Ecuador = UTC-5).', null=True, verbose_name='Inicio de campaña')),
                ('ends_at', models.DateTimeField(blank=True, help_text='Vacío = sin fecha de fin.', null=True, verbose_name='Fin de campaña')),
                ('target_cities', models.JSONField(blank=True, default=list, help_text='Vacío = todo el país. Se guardan normalizadas (sin tildes, en minúscula).', verbose_name='Ciudades')),
                ('weight', models.PositiveSmallIntegerField(default=10, help_text='A mayor peso, más veces se muestra frente a otras campañas de la misma ubicación. Peso 30 sale tres veces más que peso 10.', verbose_name='Peso')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('amount_charged_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Lo que se cobró por esta campaña. Vacío en las que no se cobran.', max_digits=9, null=True, verbose_name='Importe cobrado (USD)')),
                ('click_count', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advertiser', models.ForeignKey(blank=True, help_text='Vacío solo para el reclamo de «espacio disponible».', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='advertising.advertiser', verbose_name='Anunciante')),
            ],
            options={
                'verbose_name': 'Campaña',
                'verbose_name_plural': 'Campañas',
                'ordering': ['placement', '-weight', '-created_at'],
                'indexes': [models.Index(fields=['placement', 'is_active'], name='advertising_placeme_ce7e10_idx'), models.Index(fields=['placement', 'kind', 'is_active'], name='advertising_placeme_65e758_idx')],
            },
        ),
    ]
