/** @type {import('tailwindcss').Config} */

// Every visual value comes from app/aents-tokens.css, generated by @aents/theme
// from the Aents Brand Book. This file declares no colour, radius, shadow or
// font of its own: it only maps the token names this codebase already uses onto
// the CSS custom properties that carry them.
//
// Colours are declared twice on purpose. `--x` holds the hex, which is what most
// utilities need; `--x-rgb` holds the channel triplet, which is the only form
// Tailwind can apply an opacity modifier to. A utility written as `bg-primary/10`
// resolves through the channel variable; without it Tailwind drops the modifier
// with no build error.
const withAlpha = (channels) => `rgb(var(${channels}) / <alpha-value>)`;

module.exports = {
  darkMode: ['class'],
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    // `lib/` holds the shared label maps (property-labels.ts), and those are
    // class names too. Without this, a utility written only there is never
    // generated and renders as nothing at all — which is what happened to the
    // status overlay of a closed listing: white text on no background.
    './lib/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        // next/font's hashed family first, the Brand Book stack from the token
        // file as the fallback chain.
        sans: ['var(--font-jakarta)', 'var(--font-sans)'],
        geo: ['var(--font-jetbrains)', 'var(--font-mono)'],
      },

      // Brand Book type scale, kept under Tailwind's own class names so the
      // ~146 screens do not change: `text-sm` still exists, it now resolves to
      // the `body` variant instead of a Tailwind default.
      //
      // The first steps map exactly — both scales sit on a 4px grid — so body
      // copy does not move. The visible change is in headings from `text-3xl`
      // up and in `text-lg`, which has no 18px step in the Brand Book and
      // rounds to `h3` (20px).
      //
      // Only size and line height come from the tokens. Font weight is left to
      // the explicit `font-*` classes the codebase already uses; baking the
      // variant weight in here would silently fight hundreds of them.
      fontSize: {
        // Densidad compacta solicitada para Geo Propiedades: el texto de
        // interfaz baja ~2px respecto de la escala Aents. Los pisos de max()
        // son escalonados (10/11/12/14) para que caption < xs < sm < base se
        // mantenga también en móvil, donde el factor 0.9 empujaba los cuatro
        // pasos al mismo valor. xl resuelve al token h3 sin resta para que
        // lg y xl no colapsen; 4xl es el punto medio h1↔display2 y 7xl un
        // paso por encima de display1, de modo que cada clase responde.
        caption: ['max(10px, calc(var(--type-caption-size) - 1px))', { lineHeight: 'max(13px, calc(var(--type-caption-line) - 1px))' }],
        xs: ['max(11px, calc(var(--type-small-size) - 1px))', { lineHeight: 'max(14px, calc(var(--type-small-line) - 1px))' }],
        sm: ['max(12px, calc(var(--type-body-size) - 2px))', { lineHeight: 'max(16px, calc(var(--type-body-line) - 2px))' }],
        base: ['max(14px, calc(var(--type-bodyLarge-size) - 2px))', { lineHeight: 'max(20px, calc(var(--type-bodyLarge-line) - 2px))' }],
        lg: ['max(16px, calc(var(--type-h3-size) - 2px))', { lineHeight: 'max(22px, calc(var(--type-h3-line) - 2px))' }],
        xl: ['var(--type-h3-size)', { lineHeight: 'var(--type-h3-line)' }],
        '2xl': ['max(20px, calc(var(--type-h2-size) - 2px))', { lineHeight: 'max(26px, calc(var(--type-h2-line) - 3px))' }],
        '3xl': ['var(--type-h1-size)', { lineHeight: 'var(--type-h1-line)' }],
        '4xl': ['calc((var(--type-h1-size) + var(--type-display2-size)) / 2)', { lineHeight: 'calc((var(--type-h1-line) + var(--type-display2-line)) / 2)' }],
        '5xl': ['var(--type-display2-size)', { lineHeight: 'var(--type-display2-line)' }],
        '6xl': ['var(--type-display1-size)', { lineHeight: 'var(--type-display1-line)' }],
        '7xl': ['calc(var(--type-display1-size) + 8px)', { lineHeight: 'calc(var(--type-display1-line) + 8px)' }],
      },
      colors: {
        // Brand. The product accent (Verde Vital / Río Turquesa) is resolved
        // into --primary by the token exporter, so this app never names it.
        //
        // These names are used both as text and as button fills, and Verde Vital
        // scores 2.28:1 against white in either role — under AA. They therefore
        // map to the `-strong` variants, which are the same brand colour
        // adjusted until it passes. The pure token stays available as
        // `var(--primary)` for large surfaces and map fills.
        primary: {
          DEFAULT: withAlpha('--primary-strong-rgb'),
          foreground: withAlpha('--on-primary-rgb'),
        },
        primaryHover: withAlpha('--primary-pressed-strong-rgb'),
        primaryLight: withAlpha('--primary-soft-rgb'),
        secondary: {
          DEFAULT: withAlpha('--accent-alt-strong-rgb'),
          foreground: withAlpha('--on-accent-rgb'),
        },
        // Hover stays in the teal family. The token set has no pressed step
        // for accent-alt, so the hover brightens to the pure accent instead of
        // crossing into the primary green.
        secondaryHover: withAlpha('--accent-alt-rgb'),

        // The former navy scale, from lightest to darkest. It used to be this
        // app's source of truth; now it is a view over the shared palette.
        navy: {
          100: withAlpha('--primary-soft-rgb'),
          200: withAlpha('--lavender-rgb'),
          300: withAlpha('--accent-alt-strong-rgb'),
          400: withAlpha('--primary-strong-rgb'),
          500: withAlpha('--navy-rgb'),
        },

        // Surfaces and text.
        surface: withAlpha('--background-rgb'),
        line: withAlpha('--border-rgb'),
        dark: withAlpha('--text-rgb'),
        textPrimary: withAlpha('--text-rgb'),
        textSecondary: withAlpha('--text-secondary-rgb'),

        // State. Soft variants arrive already blended from the exporter.
        success: withAlpha('--success-strong-rgb'),
        successBg: withAlpha('--success-soft-rgb'),
        warning: withAlpha('--warning-strong-rgb'),
        warningBg: withAlpha('--warning-soft-rgb'),
        error: withAlpha('--error-strong-rgb'),
        errorBg: withAlpha('--error-soft-rgb'),

        // shadcn/ui contract. These names are consumed by the components under
        // components/ui and must keep resolving.
        background: withAlpha('--background-rgb'),
        foreground: withAlpha('--text-rgb'),
        muted: {
          DEFAULT: withAlpha('--surface-rgb'),
          foreground: withAlpha('--text-muted-rgb'),
        },
        card: {
          DEFAULT: withAlpha('--background-rgb'),
          foreground: withAlpha('--text-rgb'),
        },
        popover: {
          DEFAULT: withAlpha('--background-rgb'),
          foreground: withAlpha('--text-rgb'),
        },
        accent: {
          DEFAULT: withAlpha('--surface-rgb'),
          foreground: withAlpha('--text-rgb'),
        },
        destructive: {
          DEFAULT: withAlpha('--error-strong-rgb'),
          foreground: withAlpha('--on-primary-rgb'),
        },
        border: withAlpha('--border-rgb'),
        input: withAlpha('--border-rgb'),
        ring: withAlpha('--primary-strong-rgb'),
      },
      borderRadius: {
        // Mapped onto the Brand Book scale (0·4·8·12·16·20·24·32). The former
        // 6/7/10px steps do not exist there and round to the nearest token.
        sm: 'var(--radius-xs)',
        input: 'var(--radius-xs)',
        button: 'var(--radius-sm)',
        card: 'var(--radius-sm)',
        md: 'var(--radius-sm)',
        modal: 'var(--radius-md)',
        sidebar: 'var(--radius-md)',
        hero: 'var(--radius-md)',
        lg: 'var(--radius-md)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down var(--duration-fast) var(--easing-standard)',
        'accordion-up': 'accordion-up var(--duration-fast) var(--easing-standard)',
      },
      boxShadow: {
        // Brand Book elevation 0-5. These replace the previous green-tinted
        // shadows, which is a visible change on cards.
        soft: 'var(--shadow-1)',
        card: 'var(--shadow-1)',
        cardHover: 'var(--shadow-3)',
      },
      zIndex: {
        mapoverlay: '500',
        mapcontrol: '900',
        nav: '1000',
        backdrop: '1400',
        panel: '1500',
        modal: '2000',
        top: '9999',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
