# Generated by Django 6.0.6 on 2026-07-07 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Identificador corto, ej. 'properati'", max_length=60, unique=True)),
                ('nombre', models.CharField(help_text="Nombre visible, ej. 'Properati Ecuador'", max_length=120)),
                ('base_url', models.URLField(help_text='URL base del portal')),
                ('activa', models.BooleanField(default=True, help_text='Si se incluye al correr --all')),
                ('scraper', models.CharField(blank=True, default='', max_length=120)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Parámetros por fuente (categorías, límites, etc.)')),
                ('last_scrape_at', models.DateTimeField(blank=True, help_text='Último scraping en local', null=True)),
                ('last_import_at', models.DateTimeField(blank=True, help_text='Última importación en este entorno', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fuente',
                'verbose_name_plural': 'Fuentes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ListingCruda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=120)),
                ('source_url', models.URLField(blank=True, default='', max_length=500)),
                ('payload', models.JSONField(default=dict)),
                ('scraped_at', models.DateTimeField(auto_now=True)),
                ('fuente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crudos', to='ingesta.fuente')),
            ],
            options={
                'verbose_name': 'Anuncio crudo',
                'verbose_name_plural': 'Anuncios crudos',
                'ordering': ['-scraped_at'],
                'unique_together': {('fuente', 'external_id')},
            },
        ),
    ]
