# Generated by Django 6.0.6 on 2026-07-07 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingesta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestaRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'En ejecución'), ('done', 'Terminado'), ('error', 'Error')], default='pending', max_length=12)),
                ('limit', models.PositiveIntegerField(blank=True, help_text='Tope de anuncios (vacío = todo el país)', null=True)),
                ('con_imagenes', models.BooleanField(default=True)),
                ('solo_nuevas', models.BooleanField(default=False, help_text='Salta los anuncios ya importados y avanza a los que faltan (modo por tandas)')),
                ('vistos', models.PositiveIntegerField(default=0)),
                ('creadas', models.PositiveIntegerField(default=0)),
                ('actualizadas', models.PositiveIntegerField(default=0)),
                ('duplicadas', models.PositiveIntegerField(default=0)),
                ('sin_ubicacion', models.PositiveIntegerField(default=0)),
                ('mensaje', models.TextField(blank=True, default='')),
                ('lanzado_por', models.CharField(blank=True, default='', max_length=150)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fuente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='ingesta.fuente')),
            ],
            options={
                'verbose_name': 'Ejecución de ingesta',
                'verbose_name_plural': 'Ejecuciones de ingesta',
                'ordering': ['-created_at'],
            },
        ),
    ]
