# Generated by Django 6.0.6 on 2026-07-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingesta', '0002_ingestarun'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuente',
            name='disponibles',
            field=models.PositiveIntegerField(default=0, help_text='Total de anuncios que muestra el portal (aprox.)'),
        ),
        migrations.AddField(
            model_name='fuente',
            name='disponibles_at',
            field=models.DateTimeField(blank=True, help_text="Cuándo se contó 'disponibles'", null=True),
        ),
        migrations.AddField(
            model_name='ingestarun',
            name='caducadas',
            field=models.PositiveIntegerField(default=0, help_text='Ya no vigentes en el portal'),
        ),
        migrations.AddField(
            model_name='ingestarun',
            name='modo',
            field=models.CharField(choices=[('load', 'Cargar/actualizar desde el portal'), ('refresh', 'Actualizar existentes y verificar vigencia')], default='load', max_length=12),
        ),
    ]
