// Verifies that the vendored Aents design tokens still match the monorepo.
//
//   node scripts/check-tokens.mjs
//
// app/aents-tokens.css is a copy of an artifact generated by @aents/theme. A copy
// with no verification goes stale in weeks and quietly undoes the whole adoption,
// so this runs in CI and fails the build when the two drift apart.
//
// Comparison is by sha256 of the CSS, which is what VERSION records. Set
// AENTS_TOKENS_URL to point at a release asset; without it the check only
// validates that the local pair is internally consistent, which is what a
// contributor without network access can still do.

import { createHash } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const appDir = resolve(dirname(fileURLToPath(import.meta.url)), '../app');
const cssPath = join(appDir, 'aents-tokens.css');
const versionPath = join(appDir, 'aents-tokens.version');

const fail = (message) => {
  console.error(`✗ ${message}`);
  process.exit(1);
};

const [css, versionFile] = await Promise.all([
  readFile(cssPath, 'utf8').catch(() => fail(`missing ${cssPath}`)),
  readFile(versionPath, 'utf8').catch(() => fail(`missing ${versionPath}`)),
]);

const version = Object.fromEntries(
  versionFile
    .split('\n')
    .filter(Boolean)
    .map((line) => {
      const at = line.indexOf('=');
      return [line.slice(0, at), line.slice(at + 1)];
    })
);

const localHash = createHash('sha256').update(css).digest('hex');

if (version.sha256 !== localHash) {
  fail(
    `app/aents-tokens.css does not match its .version file.\n` +
      `  expected ${version.sha256}\n  found    ${localHash}\n` +
      `  The stylesheet was edited by hand. It is generated: re-export it from the monorepo.`
  );
}

if (version.product !== 'geoPropiedades') {
  fail(`expected the geoPropiedades bundle, found product="${version.product}"`);
}

const remote = process.env.AENTS_TOKENS_URL;
if (!remote) {
  console.log(
    `✓ tokens consistent (${localHash.slice(0, 12)}, commit ${version.commit?.slice(0, 12)})\n` +
      `  Set AENTS_TOKENS_URL to also check them against the published artifact.`
  );
  process.exit(0);
}

const response = await fetch(remote);
if (!response.ok) {
  fail(`could not fetch ${remote}: HTTP ${response.status}`);
}
const published = await response.text();
const publishedHash = createHash('sha256').update(published).digest('hex');

if (publishedHash !== localHash) {
  fail(
    `the vendored tokens are behind the published ones.\n` +
      `  published ${publishedHash}\n  vendored  ${localHash}\n` +
      `  Copy the artifact again and review what changed before committing.`
  );
}

console.log(`✓ tokens up to date with ${remote} (${localHash.slice(0, 12)})`);
