# Generated by Django 6.0.8 on 2026-08-11 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=90, unique=True)),
                ('description', models.TextField(blank=True, help_text='Aparece bajo el título en la página de la categoría y en su meta description.', verbose_name='Descripción')),
                ('order', models.PositiveSmallIntegerField(default=100, help_text='Menor número aparece antes en el menú del blog.', verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(help_text='Parte final de la URL: /blog/<slug>. No la cambies una vez indexada.', max_length=220, unique=True)),
                ('excerpt', models.TextField(help_text='Entradilla del listado y meta description por defecto (150-160 caracteres ideal).', max_length=400, verbose_name='Resumen')),
                ('body', models.TextField(help_text='Markdown: ## y ### para títulos, - para listas, 1. para listas numeradas, **negrita**, [texto](/enlace), > para citas.', verbose_name='Cuerpo (Markdown)')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Lista JSON de textos cortos, p. ej. ["Quito", "Hipotecas"].', verbose_name='Etiquetas')),
                ('faqs', models.JSONField(blank=True, default=list, help_text='Lista JSON [{"q": "pregunta", "a": "respuesta"}]. Se publican como FAQPage en JSON-LD: es lo que Google y los buscadores de IA citan.', verbose_name='Preguntas frecuentes')),
                ('related_links', models.JSONField(blank=True, default=list, help_text='Lista JSON [{"label": "texto", "href": "/ruta"}].', verbose_name='Enlaces relacionados')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/covers/', verbose_name='Imagen de portada')),
                ('cover_image_alt', models.CharField(blank=True, max_length=200, verbose_name='Texto alternativo de la portada')),
                ('author_name', models.CharField(blank=True, help_text='Si se deja vacío se firma con el nombre del sitio.', max_length=120, verbose_name='Autor (nombre público)')),
                ('author_role', models.CharField(blank=True, max_length=160, verbose_name='Cargo o credencial del autor')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('scheduled', 'Programado'), ('published', 'Publicado'), ('archived', 'Archivado')], db_index=True, default='draft', max_length=12, verbose_name='Estado')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, help_text='En el futuro = programado: el post aparece solo cuando llega la fecha. Hora en UTC (Ecuador = UTC-5, así que las 13:00 UTC son las 08:00 locales).', null=True, verbose_name='Fecha de publicación')),
                ('is_featured', models.BooleanField(default=False, help_text='Se muestra en grande en la portada del blog.', verbose_name='Destacado')),
                ('meta_title', models.CharField(blank=True, help_text='Solo si debe diferir del título. Vacío = se usa el título.', max_length=200, verbose_name='Meta title')),
                ('meta_description', models.CharField(blank=True, help_text='Vacío = se usa el resumen.', max_length=320, verbose_name='Meta description')),
                ('reading_minutes', models.PositiveSmallIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Autor (cuenta)')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['status', 'published_at'], name='blog_post_status_5b2843_idx')],
            },
        ),
    ]
