# Generated by Django 6.0.8 on 2026-08-11 18:12

from django.db import migrations, models
from django.utils.text import slugify


def backfill_author_slugs(apps, schema_editor):
    """Posts written before the author page existed still need their entity."""
    Post = apps.get_model("blog", "Post")
    for post in Post.objects.exclude(author_name="").only("id", "author_name"):
        Post.objects.filter(pk=post.pk).update(
            author_slug=slugify(post.author_name)[:140]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_seed_guides'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_slug',
            field=models.SlugField(blank=True, editable=False, max_length=140, verbose_name='Slug del autor'),
        ),
        migrations.AddField(
            model_name='post',
            name='city',
            field=models.CharField(blank=True, db_index=True, help_text='Ciudad sobre la que trata el artículo, p. ej. «Quito». Escrita igual que en los anuncios. Vacío = alcance nacional.', max_length=80, verbose_name='Ciudad del artículo'),
        ),
        migrations.RunPython(backfill_author_slugs, migrations.RunPython.noop),
    ]
