# Generated by Django 6.0.8 on 2026-08-21 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0003_campaign_target_provinces'),
        ('blog', '0007_drop_sponsorships'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sponsor',
            field=models.ForeignKey(blank=True, help_text='Vacío = contenido editorial. Con anunciante = contenido publicitario.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsored_posts', to='advertising.advertiser', verbose_name='Anunciante'),
        ),
        migrations.AddField(
            model_name='post',
            name='sponsor_kind',
            field=models.CharField(blank=True, choices=[('paid', 'Pagada'), ('partner', 'Del grupo (sin coste)'), ('promo', 'Espacio disponible')], default='', help_text='Pagada por un tercero, o del grupo (Aents) sin coste.', max_length=10, verbose_name='Tipo de publicidad'),
        ),
    ]
