/**
 * Promotion kit: the formats, links and copy handed to whoever publishes.
 *
 * The kit exists because the minute after publishing is the only one in which
 * someone has both the urge to show their listing and the listing in front of
 * them. Everything here is built to be pasted, not read: the copy is finished
 * text, the links already carry their attribution, and nothing needs a decision
 * before it can be used.
 *
 * The copy is composed from templates rather than generated by a model. Whoever
 * publishes will paste it without reading it to the end, so a sentence that
 * promises a garage the listing does not have becomes the portal's problem, not
 * the template's. See SOC-007.
 */

import { SITE_URL } from './properties';
import {
  formatArea,
  formatPrice,
  getPropertyTypeLabel,
  getStatusLabel,
} from './property-labels';
import type { Property } from './types';

export type SocialNetwork = 'facebook' | 'instagram' | 'tiktok' | 'whatsapp';

export type SocialFormat = 'feed' | 'portrait' | 'story' | 'map' | 'og';

export type CopyTone = 'cercano' | 'formal' | 'urgente';

export interface FormatSpec {
  width: number;
  height: number;
  /** Shown on the kit screen, in Spanish, because a person reads it. */
  label: string;
  hint: string;
}

/**
 * Every lamina the kit can produce.
 *
 * The portrait 4:5 is not redundant with the square: Instagram gives a 4:5 post
 * noticeably more screen than a 1:1 in the feed, and that is free reach for the
 * same photo.
 */
export const SOCIAL_FORMATS: Record<SocialFormat, FormatSpec> = {
  feed: {
    width: 1080,
    height: 1080,
    label: 'Cuadrada 1:1',
    hint: 'Feed de Facebook e Instagram',
  },
  portrait: {
    width: 1080,
    height: 1350,
    label: 'Vertical 4:5',
    hint: 'Feed de Instagram, ocupa más pantalla',
  },
  story: {
    width: 1080,
    height: 1920,
    label: 'Historia 9:16',
    hint: 'Historias, Reels y portada de TikTok',
  },
  map: {
    width: 1080,
    height: 1080,
    label: 'Mapa',
    hint: 'Dónde queda exactamente',
  },
  og: {
    width: 1200,
    height: 630,
    label: 'Vista previa del enlace',
    hint: 'Lo que se ve al pegar el enlace en una publicación',
  },
};

export const NETWORK_LABELS: Record<SocialNetwork, string> = {
  facebook: 'Facebook',
  instagram: 'Instagram',
  tiktok: 'TikTok',
  whatsapp: 'WhatsApp',
};

export const COPY_TONES: Record<CopyTone, string> = {
  cercano: 'Cercano',
  formal: 'Formal',
  urgente: 'Con urgencia',
};

/** Which laminas are worth offering for each network, best first. */
export const NETWORK_FORMATS: Record<SocialNetwork, SocialFormat[]> = {
  facebook: ['feed', 'map', 'og'],
  instagram: ['portrait', 'story', 'map', 'feed'],
  // TikTok wants video. The 9:16 works as a cover or inside its photo mode,
  // and saying so is more useful than pretending a PNG is a post.
  tiktok: ['story', 'map'],
  whatsapp: ['feed', 'map'],
};

/**
 * How to actually publish, per network.
 *
 * Written because the honest answer to "can it post for me?" is no (SOC-010),
 * and the next best thing is not leaving someone staring at a downloaded PNG
 * wondering what to do with it.
 */
export const NETWORK_STEPS: Record<SocialNetwork, string[]> = {
  facebook: [
    'Descarga la imagen o compártela directo desde tu celular.',
    'Copia el texto y pégalo al crear la publicación.',
    'Si prefieres, pega solo el enlace: Facebook arma la vista previa solo.',
  ],
  instagram: [
    'Descarga la imagen (la vertical rinde más que la cuadrada).',
    'Copia el texto y pégalo como descripción al publicar.',
    'Instagram no deja enlaces en la descripción: pon el enlace en tu biografía. El QR de la imagen y el código funcionan igual.',
  ],
  tiktok: [
    'Usa la imagen 9:16 como portada, o súbela en modo foto.',
    'Copia el gancho y pégalo como descripción.',
    'Si grabas un video del recorrido, la lámina del mapa funciona bien como cierre.',
  ],
  whatsapp: [
    'Comparte la imagen desde tu celular y pega el texto como mensaje.',
    'En estados de WhatsApp funciona mejor la imagen vertical.',
  ],
};

// --- Links ----------------------------------------------------------------

/**
 * The short URL a code resolves to.
 *
 * Kept short on purpose: it gets printed onto an image and typed by hand from
 * it, so every character is one more chance to get it wrong.
 */
export function shortUrl(property: Pick<Property, 'id' | 'short_code'>): string {
  return property.short_code
    ? `${SITE_URL}/p/${property.short_code}`
    : `${SITE_URL}/propiedad/${property.id}`;
}

/**
 * The same URL, tagged with where the visit will have come from.
 *
 * Without this the kit is an act of faith: whoever shares cannot tell whether it
 * did anything, and stops. See SOC-008.
 */
export function trackedUrl(
  property: Pick<Property, 'id' | 'short_code'>,
  network: SocialNetwork
): string {
  const params = new URLSearchParams({
    utm_source: network,
    utm_medium: 'social',
    utm_campaign: 'owner_kit',
  });
  return `${shortUrl(property)}?${params.toString()}`;
}

/**
 * Path of a generated lamina, relative to the current origin.
 *
 * What the kit screen and the download button use. Relative because the screen
 * has to work on whatever host it is being served from, and `SITE_URL` is the
 * canonical production address even in development.
 */
export function laminaPath(
  property: Pick<Property, 'id'>,
  format: SocialFormat,
  network: SocialNetwork = 'facebook'
): string {
  return `/api/social/${property.id}/${format}?red=${network}`;
}

/**
 * Absolute URL of a lamina, for metadata.
 *
 * Link previews are fetched by a crawler with no notion of the current origin,
 * so the `og:image` has to spell the host out.
 */
export function laminaUrl(
  property: Pick<Property, 'id'>,
  format: SocialFormat,
  network: SocialNetwork = 'facebook'
): string {
  return `${SITE_URL}${laminaPath(property, format, network)}`;
}

/** The file someone ends up with in their downloads folder. */
export function laminaFilename(
  property: Pick<Property, 'id' | 'short_code'>,
  format: SocialFormat
): string {
  return `geopropiedades-${property.short_code ?? property.id}-${format}.png`;
}

// --- Copy -----------------------------------------------------------------

const TYPE_HASHTAGS: Record<string, string[]> = {
  house: ['CasasEnVenta', 'CasaPropia'],
  apartment: ['Departamentos', 'DepartamentoEnVenta'],
  land: ['Terrenos', 'TerrenoEnVenta', 'Lotes'],
  commercial: ['LocalComercial', 'Negocios'],
  other: ['Inmuebles'],
};

/** Strip accents and spaces: a hashtag with a tilde breaks on some clients. */
function toHashtag(value: string): string {
  const clean = value
    .normalize('NFD')
    // Same escaped range as `slugify`: written literally it is invisible in an
    // editor and one stray keystroke away from matching nothing.
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-zA-Z0-9\s]/g, '')
    .trim()
    .split(/\s+/)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join('');
  return clean ? `#${clean}` : '';
}

export function buildHashtags(property: Property): string[] {
  const typeTags = TYPE_HASHTAGS[property.property_type] ?? TYPE_HASHTAGS.other;
  const tags = [
    ...typeTags.map((tag) => `#${tag}`),
    toHashtag(property.city ?? ''),
    toHashtag(property.province ?? ''),
    '#BienesRaicesEcuador',
    '#Ecuador',
    property.status === 'for_rent' ? '#Arriendo' : '#EnVenta',
  ];
  // A tag built from an empty city comes back as '', and duplicates happen when
  // the city and the province share a name (Loja, Azogues, El Oro…).
  return Array.from(new Set(tags.filter(Boolean)));
}

/**
 * The listing's factual attributes, as phrases.
 *
 * Only what the listing actually declares: a missing field disappears from the
 * sentence instead of being written as "0 habitaciones". SOC-007.
 */
export function buildFacts(property: Property): string[] {
  const facts: string[] = [];
  const area = formatArea(property.area);
  if (area) facts.push(area);
  if ((property.rooms ?? 0) > 0) {
    facts.push(`${property.rooms} ${property.rooms === 1 ? 'habitación' : 'habitaciones'}`);
  }
  if ((property.bathrooms ?? 0) > 0) {
    facts.push(`${property.bathrooms} ${property.bathrooms === 1 ? 'baño' : 'baños'}`);
  }
  if ((property.parking_spaces ?? 0) > 0) {
    facts.push(
      `${property.parking_spaces} ${property.parking_spaces === 1 ? 'parqueadero' : 'parqueaderos'}`
    );
  }
  return facts;
}

/** "Casa en venta en Macas, Morona Santiago" — omitting whatever is missing. */
export function buildHeadline(property: Property): string {
  const type = getPropertyTypeLabel(property.property_type);
  const status = getStatusLabel(property.status).toLowerCase();
  const place = [property.city, property.province].filter(Boolean).join(', ');
  return place ? `${type} ${status} en ${place}` : `${type} ${status}`;
}

/**
 * The price line.
 *
 * `formatPrice` already answers "Precio a consultar" for a null price, which is
 * what keeps a lamina from ever printing "$0" over a listing whose price was
 * deliberately left empty (PROP-004, SOC-005).
 */
export function buildPriceLine(property: Property): string {
  const main = formatPrice(property.price);
  const rent = property.rent_price != null ? formatPrice(property.rent_price) : '';
  if (rent && rent !== 'Precio a consultar') {
    return `${main} venta · ${rent}/mes alquiler`;
  }
  return property.status === 'for_rent' && main !== 'Precio a consultar'
    ? `${main}/mes`
    : main;
}

const OPENERS: Record<CopyTone, (headline: string) => string> = {
  cercano: (headline) => `🏡 ${headline}`,
  formal: (headline) => `${headline}.`,
  urgente: (headline) => `🔥 ¡No te lo pierdas! ${headline}`,
};

const CLOSERS: Record<CopyTone, string> = {
  cercano: 'Mira las fotos y la ubicación exacta en el mapa 👇',
  formal: 'Fotografías y ubicación exacta disponibles en el enlace:',
  urgente: '¡Escríbeme hoy! Mira dónde queda exactamente 👇',
};

function excerpt(text: string | undefined, max: number): string {
  if (!text) return '';
  const clean = text.replace(/\s+/g, ' ').trim();
  if (clean.length <= max) return clean;
  // Cut on a word boundary; a description sliced mid-word reads like a bug.
  return `${clean.slice(0, clean.lastIndexOf(' ', max))}…`;
}

/**
 * Finished text for one network.
 *
 * The three networks get genuinely different shapes, not the same paragraph
 * truncated: Facebook rewards a full description, Instagram a short block with
 * tags, and TikTok a two-line hook that has to work as a spoken caption.
 */
export function buildCopy(
  property: Property,
  network: SocialNetwork,
  tone: CopyTone = 'cercano'
): string {
  const headline = buildHeadline(property);
  const price = buildPriceLine(property);
  const facts = buildFacts(property);
  const code = property.short_code ?? '';
  const url = trackedUrl(property, network);
  const factLine = facts.join(' · ');
  const codeLine = code ? `Código del anuncio: ${code}` : '';

  if (network === 'facebook') {
    return [
      OPENERS[tone](headline),
      '',
      [price, factLine].filter(Boolean).join(' · '),
      excerpt(property.description, 320),
      '',
      CLOSERS[tone],
      url,
      '',
      codeLine,
      buildHashtags(property).slice(0, 6).join(' '),
    ]
      .filter((line) => line !== undefined)
      .join('\n')
      .replace(/\n{3,}/g, '\n\n')
      .trim();
  }

  if (network === 'instagram') {
    return [
      OPENERS[tone](headline),
      [price, factLine].filter(Boolean).join(' · '),
      '',
      'Ubicación exacta en el mapa 📍 Enlace en la biografía o escanea el QR.',
      codeLine,
      '',
      buildHashtags(property).join(' '),
    ]
      .join('\n')
      .replace(/\n{3,}/g, '\n\n')
      .trim();
  }

  if (network === 'tiktok') {
    const place = property.city || property.province || 'Ecuador';
    const hook =
      tone === 'urgente'
        ? `Se va rápido: ${getPropertyTypeLabel(property.property_type).toLowerCase()} en ${place} por ${price} 👀`
        : `Esto en ${place} cuesta ${price} 👀`;
    return [
      hook,
      factLine ? `${factLine}. Te muestro dónde queda exactamente 📍` : 'Te muestro dónde queda exactamente 📍',
      '',
      codeLine ? `${codeLine} · geopropiedadesecuador.com` : 'geopropiedadesecuador.com',
      buildHashtags(property).slice(0, 5).join(' ').toLowerCase(),
    ]
      .join('\n')
      .trim();
  }

  // WhatsApp: no hashtags, no emoji wall — it is a message to one person.
  return [
    headline,
    [price, factLine].filter(Boolean).join(' · '),
    '',
    'Fotos y ubicación exacta:',
    url,
  ]
    .join('\n')
    .trim();
}
